### ISSUE TITLE
Crash when pointing to single file

### ISSUE THREAD

**Issue by gideonw** [filebot/filebot-node#21]
I cannot run FB on the entire directory so sometimes I need to point it at a single file, well this crashes the dropdown search, but FB processes the file just fine.

```javascript
GET: /folders?q=%2Fdata%2Ffile.mkv
fs.js:914
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOTDIR: not a directory, scandir '/data/file.mkv'
    at Object.fs.readdirSync (fs.js:914:18)
    at listFolders (/usr/local/filebot-node/server/app.js:238:12)
    at handleRequest (/usr/local/filebot-node/server/app.js:303:20)
    at Server.server (/usr/local/filebot-node/server/app.js:533:16)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:194:7)
    at parserOnIncoming (_http_server.js:565:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by rednoah** [comment]
Yep, that's a bug. Thanks for reporting it.

Unfortunately, I currently don't have time to work on this project and publish new releases. I'd be happy to accept a pull request though.
