### ISSUE TITLE
After upgrading to 0.2.9 on Synology getting parsing failed errors

### ISSUE THREAD

**Issue by vvvlad** [filebot/filebot-node#27]
```
org.codehaus.groovy.control.CompilationFailedException: parsing failed
org.codehaus.groovy.control.CompilationFailedException: parsing failed
	at org.apache.groovy.parser.antlr4.AstBuilder.createParsingFailedException(AstBuilder.java:4538)
	at org.apache.groovy.parser.antlr4.AstBuilder.convertException(AstBuilder.java:416)
	at org.apache.groovy.parser.antlr4.AstBuilder.buildAST(AstBuilder.java:426)
	at org.apache.groovy.parser.antlr4.Antlr4ParserPlugin.buildAST(Antlr4ParserPlugin.java:58)
	at net.filebot.cli.ScriptShell.evaluate(Unknown Source)
	at net.filebot.cli.ScriptShell.runScript(Unknown Source)
	at net.filebot.cli.ArgumentProcessor.runScript(Unknown Source)
	at net.filebot.cli.ArgumentProcessor.run(Unknown Source)
	at net.filebot.Main.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
```

**Comment by rednoah** [comment]
https://www.filebot.net/forums/viewtopic.php?f=8&t=11697
